# Generated by Django 3.0.7 on 2020-06-16 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=255)),
                ('types', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('img', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='aplication.Producto')),
            ],
        ),
    ]
